-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


	CREATE TABLE IF NOT EXISTS public.iot
	(
		id_iot integer NOT NULL DEFAULT nextval('iot_id_iot_seq'::regclass),
		id_owner integer,
		CONSTRAINT iot_pkey PRIMARY KEY (id_iot)
	);

CREATE TABLE IF NOT EXISTS public.owner
(
    id_owner integer NOT NULL DEFAULT nextval('owner_id_owner_seq'::regclass),
    name_owner character varying(255) COLLATE pg_catalog."default",
    mail_owner character varying(255) COLLATE pg_catalog."default",
    password_owner character varying(255) COLLATE pg_catalog."default",
    id_iot integer,
    availability_iot boolean,
    role text COLLATE pg_catalog."default" DEFAULT 'owner'::text,
    CONSTRAINT owner_pkey PRIMARY KEY (id_owner)
);

CREATE TABLE IF NOT EXISTS public.sensor_data
(
    id_sensor integer NOT NULL DEFAULT nextval('sensor_data_id_sensor_seq'::regclass),
    humidity double precision,
    temperature double precision,
    noise double precision,
    illumination double precision,
    id_iot integer,
    date time without time zone,
    CONSTRAINT sensor_data_pkey PRIMARY KEY (id_sensor)
);

CREATE TABLE IF NOT EXISTS public.worker
(
    id_worker integer NOT NULL DEFAULT nextval('worker_id_worker_seq'::regclass),
    mail_worker character varying(255) COLLATE pg_catalog."default",
    usually_sleep_start_time time with time zone,
    usually_sleep_end_time time with time zone,
    usually_peak_productivity_time time with time zone,
    usually_lowest_productivity_time time with time zone,
    id_owner integer,
    name_worker character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT worker_pkey PRIMARY KEY (id_worker)
);

CREATE TABLE IF NOT EXISTS public.worker_data
(
    id_worker_data integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_worker integer NOT NULL,
    id_sensor integer NOT NULL,
    stress_level integer,
    sleep_quality integer,
    energy_level integer,
    sleep_start_time time with time zone,
    sleep_end_time time with time zone,
    comment text COLLATE pg_catalog."default",
    record_date timestamp without time zone,
    record_time timestamp without time zone[],
    CONSTRAINT worker_data_pkey PRIMARY KEY (id_worker_data)
);

ALTER TABLE IF EXISTS public.iot
    ADD CONSTRAINT iot_id_owner_fkey FOREIGN KEY (id_owner)
    REFERENCES public.owner (id_owner) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.owner
    ADD CONSTRAINT owner_id_iot_fkey FOREIGN KEY (id_iot)
    REFERENCES public.iot (id_iot) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sensor_data
    ADD CONSTRAINT sensor_data_id_iot_fkey FOREIGN KEY (id_iot)
    REFERENCES public.iot (id_iot) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.worker
    ADD CONSTRAINT worker_id_owner_fkey FOREIGN KEY (id_owner)
    REFERENCES public.owner (id_owner) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;